# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13eeAbY05pIiXCqx3N1cmeIGQD2m32b3i
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#input data pada file csv ke variabel 'dataframe'
dataframe = pd.read_csv('/content/sample_data/high_diamond_ranked_10min.csv')

#cek ukuran dataset
print(dataframe.shape) #9879 baris x 40 kolom

#cek nama kolom dataframe
print(dataframe.columns)

#cek isi data (5 baris pertama)
print(dataframe.head())

#hapus kolom gameId karena tidak diperlukan
dataframe.drop(['gameId'], axis=1, inplace=True)

#cek missing values
print(dataframe.isna().sum())

correlation = dataframe.corr()

P_corr = correlation.loc['blueWins'].sort_values(ascending=False)[1:6]
N_corr = correlation.loc['blueWins'].sort_values(ascending=True)[:5]

#cek korelasi antar variabel pada dataframe
print(P_corr)
print(N_corr)

plt.figure(figsize=(15,15))
sns.heatmap(correlation,
xticklabels=dataframe.columns,
yticklabels=dataframe.columns,
annot=False)

dataframe.plot(kind = 'scatter',
x = 'blueGoldDiff',
y = 'blueWins',
figsize=(10,10))

neg_gold_diff = 0
pos_gold_diff = 0
total = 0

for index, row in dataframe.iterrows():
  if row['blueGoldDiff'] > 0 and row['blueWins'] == 1:
    pos_gold_diff += 1
    total += 1
  elif row['blueGoldDiff'] < 0 and row['blueWins'] == 1:
    neg_gold_diff += 1
    total += 1

percentage_neg_gold_diff = neg_gold_diff * 100 / total
percentage_pos_gold_diff = pos_gold_diff * 100 / total

print('negative blue gold difference wins: %.2f' % percentage_neg_gold_diff + '%')
print('positive blue gold difference wins: %.2f' % percentage_pos_gold_diff + '%')

x = ['negative_blueGoldDiff', 'positive_blueGoldDiff']
y = [percentage_neg_gold_diff, percentage_pos_gold_diff]

fig, ax = plt.subplots()
ind = np.arange(len(y))
width = 0.75
ax.barh(ind, y, width, color="blue")
ax.set_yticks(ind+width/2)
ax.set_yticklabels(x, minor=False)
plt.title('percentage of games where blue team wins with negative/positive gold difference')
plt.show()